version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  database:
    image: percona:8.0.32-24
    restart: always
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: "/usr/bin/mysql -uroot -proot --execute \"USE docker_db; SELECT id FROM docker_healthcheck;\""
      interval: 30s
      timeout: 5s
      retries: 5

  ab:
    build:
      context: ./ab
      dockerfile: Dockerfile
